{{- if and .Values.persistence.enabled (eq .Values.storage.backend "sqlite") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "axiom.fullname" . }}
  labels:
    {{- include "axiom.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
